on:
  push:
    tags:
      - v*

name: Release

permissions:
  contents: read
  checks: write

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release:
    name: Create draft release
    needs:
      - test
    runs-on: ubuntu-latest
    permissions:
      # Needed to create the release
      contents: write
    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v3
        with:
          name: journald-exporter
      - name: Generate draft release
        run: |
          gh release create "$VERSION_NAME" journald-exporter \
            --generate-notes \
            --draft \
            --target main \
            --title "$VERSION_NAME" \
            --verify-tag
        env:
          VERSION_NAME: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
