on:
  workflow_call:
    outputs:
      run_id:
        value: ${{ github.run_id }}

name: Test

env:
  RUSTFLAGS: "-Dwarnings"
  RUST_BACKTRACE: full

# Only allow Git repo access to start.
permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install libsystemd-dev
      - uses: actions/checkout@v3
      - name: Install Rustup (if needed)
        run: |
          if ! command -v rustup &>/dev/null; then
            curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused -fsSL "https://sh.rustup.rs" | sh -s -- --default-toolchain none -y
            echo "${CARGO_HOME:-$HOME/.cargo}/bin" >> $GITHUB_PATH
          fi
      - run: rustup toolchain install stable --profile minimal --component clippy --component rustfmt
      - run: shellcheck ./scripts/*.sh
      - run: cargo clippy --all-targets
      - run: cargo fmt --all --check

  build:
    name: Build
    needs:
      - lint
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    steps:
      - name: Show GLIBC version
        run: ldd --version
      - run: yum makecache
      - run: yum -y install systemd-devel epel-release
      - run: yum -y install jq
      - uses: actions/checkout@v3
      - name: Install Rustup (if needed)
        # This lacks the `--retry-connrefused` flag as the version of curl here is pretty ancient
        run: |
          if ! command -v rustup &>/dev/null; then
            curl --proto '=https' --tlsv1.2 --retry 10 -fsSL "https://sh.rustup.rs" | sh -s -- --default-toolchain none -y
            echo "${CARGO_HOME:-$HOME/.cargo}/bin" >> $GITHUB_PATH
          fi
      - run: rustup toolchain install stable --profile minimal
      - name: Build debug test binary
        # Have to copy it out to a stable filename so it'll download with a predictable filename
        # for some reason.
        run: |
          FILENAME="$(cargo test --no-run --message-format=json | jq -r 'select(.profile.test).filenames[]')" && \
          cp $FILENAME ./test-debug
      - name: Build release test binary
        # Have to copy it out to a stable filename so it'll download with a predictable filename
        # for some reason.
        run: |
          FILENAME="$(cargo test --release --no-run --message-format=json | jq -r 'select(.profile.test).filenames[]')" && \
          cp $FILENAME ./test-release
      - name: Build release binary
        run: cargo build --release
      - name: Upload release artifact
        uses: actions/upload-artifact@v3
        with:
          name: journald-exporter
          path: target/release/journald-exporter
          if-no-files-found: error
      - name: Upload debug unit test artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-debug
          path: test-debug
          if-no-files-found: error
          # Much shorter retention period as it's mostly used for testing and could get large.
          retention-days: 7
      - name: Upload release unit test artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-release
          path: test-release
          if-no-files-found: error
          # Much shorter retention period as it's mostly used for testing and could get large.
          retention-days: 7

  unit_tests:
    name: Unit tests
    needs:
      - build
    strategy:
      matrix:
        os:
        - ubuntu-20.04
        - ubuntu-22.04
        binary:
        - test-debug
        - test-release
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.binary }}
      - run: chmod +x ${{ matrix.binary }}
      - name: Test
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 2
          command: ./${{ matrix.binary }} --show-output
          # Usually passes the second try if it flakes the first.
          max_attempts: 3

  miri_tests:
    name: Miri tests
    needs:
      - unit_tests
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install libsystemd-dev
      - uses: actions/checkout@v3
      - name: Install Rustup (if needed)
        run: |
          if ! command -v rustup &>/dev/null; then
            curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused -fsSL "https://sh.rustup.rs" | sh -s -- --default-toolchain none -y
            echo "${CARGO_HOME:-$HOME/.cargo}/bin" >> $GITHUB_PATH
          fi
      - run: rustup toolchain install nightly --profile minimal --component miri
      - run: rustup override set nightly
      - run: cargo +nightly miri setup
      - run: cargo +nightly miri test --all-targets -- --show-output

  e2e_tests:
    name: End-to-end tests (release)
    needs:
      - unit_tests
    strategy:
      matrix:
        os:
        - ubuntu-20.04
        - ubuntu-22.04
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: journald-exporter
      - run: chmod +x journald-exporter
      - run: sudo node ./scripts/e2e.js -b journald-exporter
